# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-05 10:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
                name = 'Notification',
                fields = [
                    ('id', models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                    ('date', models.DateTimeField(auto_now = True, db_index = True)),
                    ('detail', models.TextField()),
                    ('read', models.BooleanField(default = False)),
                    ('deleted', models.BooleanField(default = False)),
                ],
                options = {
                    'ordering': ['-date'],
                },
        ),
        migrations.CreateModel(
                name = 'UserProfile',
                fields = [
                    ('user', models.OneToOneField(on_delete = django.db.models.deletion.CASCADE, primary_key = True, related_name = 'profile', serialize = False,
                                                  to = settings.AUTH_USER_MODEL, verbose_name = 'user')),
                    ('avatar', models.TextField()),
                    ('has_notification', models.BooleanField(default = False)),
                ],
                options = {
                    'db_table': 'user_profile',
                },
        ),
        migrations.AddField(
                model_name = 'notification',
                name = 'user',
                field = models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, related_name = 'notifications', to = settings.AUTH_USER_MODEL),
        ),
    ]
